/*
 * *
 *  * ConvertListToMap.kt
 *  * Created by Rafsan Ahmad on 3/23/25, 3:05PM
 *  * Copyright (c) 2025 . All rights reserved.
 *  *
 *
 */

package kotlinclasses.Collections

class ConvertListToMap {
    /*In Kotlin, you can convert a list of objects to a map using the associateBy
    function or associate function, depending on the structure you want for the map.
    Here's how to do it:

1. Using associateBy:
The associateBy function transforms a list into a map where the key is generated by a
specified selector function (usually a property of the object).

2. Using associate:
The associate function allows you to specify both the key and the value of the map.

3. In Kotlin, associateTo is a function that allows you to add elements to an existing map
instead of creating a new one. It operates similarly to associate or associateBy, but instead
of returning a new map, it populates the map you provide.

*/

    data class Person(val id: Int, val name: String)

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            val people = listOf(
                Person(1, "Alice"),
                Person(2, "Bob"),
                Person(3, "Charlie")
            )

            // Convert the list to a map using the `id` as the key
            val personMap = people.associateBy { it.id }

            // Print the resulting map
            println(personMap)
            //Output:
            //{1=Person(id=1, name=Alice), 2=Person(id=2, name=Bob), 3=Person(id=3, name=Charlie)}

            // Convert the list to a map where the key is the `id` and the value is the `name`
            val personMap2 = people.associate { it.id to it.name }

            // Print the resulting map
            println(personMap2)
            //output:
            //{1=Alice, 2=Bob, 3=Charlie}

            // Create an empty mutable map
            val personMap3 = mutableMapOf<Int, String>()

            // Use associateTo to add entries to the existing map
            people.associateTo(personMap3) { it.id to it.name }

            // Print the resulting map
            println(personMap3)
            //{1=Alice, 2=Bob, 3=Charlie}
        }
    }
}